/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AccountCard {
        "account": any;
        "readMore": boolean;
    }
    interface AccountsList {
        "data": any;
        "readMore": boolean;
    }
    interface EditAccount {
        "data": any;
    }
    interface ExampleComponent {
    }
    interface MyApp {
    }
}
declare global {
    interface HTMLAccountCardElement extends Components.AccountCard, HTMLStencilElement {
    }
    var HTMLAccountCardElement: {
        prototype: HTMLAccountCardElement;
        new (): HTMLAccountCardElement;
    };
    interface HTMLAccountsListElement extends Components.AccountsList, HTMLStencilElement {
    }
    var HTMLAccountsListElement: {
        prototype: HTMLAccountsListElement;
        new (): HTMLAccountsListElement;
    };
    interface HTMLEditAccountElement extends Components.EditAccount, HTMLStencilElement {
    }
    var HTMLEditAccountElement: {
        prototype: HTMLEditAccountElement;
        new (): HTMLEditAccountElement;
    };
    interface HTMLExampleComponentElement extends Components.ExampleComponent, HTMLStencilElement {
    }
    var HTMLExampleComponentElement: {
        prototype: HTMLExampleComponentElement;
        new (): HTMLExampleComponentElement;
    };
    interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {
    }
    var HTMLMyAppElement: {
        prototype: HTMLMyAppElement;
        new (): HTMLMyAppElement;
    };
    interface HTMLElementTagNameMap {
        "account-card": HTMLAccountCardElement;
        "accounts-list": HTMLAccountsListElement;
        "edit-account": HTMLEditAccountElement;
        "example-component": HTMLExampleComponentElement;
        "my-app": HTMLMyAppElement;
    }
}
declare namespace LocalJSX {
    interface AccountCard {
        "account"?: any;
        "onDeleteUser"?: (event: CustomEvent<string>) => void;
        "readMore"?: boolean;
    }
    interface AccountsList {
        "data"?: any;
        "readMore"?: boolean;
    }
    interface EditAccount {
        "data"?: any;
    }
    interface ExampleComponent {
    }
    interface MyApp {
    }
    interface IntrinsicElements {
        "account-card": AccountCard;
        "accounts-list": AccountsList;
        "edit-account": EditAccount;
        "example-component": ExampleComponent;
        "my-app": MyApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "account-card": LocalJSX.AccountCard & JSXBase.HTMLAttributes<HTMLAccountCardElement>;
            "accounts-list": LocalJSX.AccountsList & JSXBase.HTMLAttributes<HTMLAccountsListElement>;
            "edit-account": LocalJSX.EditAccount & JSXBase.HTMLAttributes<HTMLEditAccountElement>;
            "example-component": LocalJSX.ExampleComponent & JSXBase.HTMLAttributes<HTMLExampleComponentElement>;
            "my-app": LocalJSX.MyApp & JSXBase.HTMLAttributes<HTMLMyAppElement>;
        }
    }
}
